//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace novo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Academico()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int Id_Academico { get; set; }
        public string Nome { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Id_Materia { get; set; }
        public bool Ativo { get; set; }
        public bool Excluido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
