//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio_17_10_19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materia()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int Id_Materia { get; set; }
        public string Descricao { get; set; }
        public string Conteudo { get; set; }
        public Nullable<bool> Disponivel { get; set; }
        public Nullable<bool> Excluido { get; set; }
        public Nullable<int> Id_Academico { get; set; }
    
        public virtual Academico Academico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Nota { get; set; }
    }
}
