//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio_17_10_19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int Id_Nota { get; set; }
        public int Id_Materia { get; set; }
        public string Nota_Materia { get; set; }
        public decimal Nota_I { get; set; }
        public decimal Nota_II { get; set; }
        public decimal Nota_III { get; set; }
        public decimal Nota_IIII { get; set; }
    
        public virtual Materia Materia { get; set; }
    }
}
